### ISSUE TITLE
Python files for generating models are missing for some models

### ISSUE THREAD

**Issue by rogancarr** [dotnet/machinelearning-testdata#11]
I noticed that some models, like `Cifar`, don't have python files to show how they were specified and trained. This would be helpful to have for writing tests on the ML.NET TensorFlow stack.

Also, should we agree on a standard location and format for these files?

**Comment by rogancarr** [comment]
@zeahmed @abgoswam

**Comment by zeahmed** [comment]
I see that the following models don't have information regarding how the model was created.

1. cifar_model
2. cifar_saved_model
3. minist_model

@abgoswam, Where did you get these model when you added them here? Did I create anyone of them?

**Comment by ericstj** [comment]
We're archiving this public repo.
